#!/usr/bin/env bun
/**
 * Reads dist/web/ and generates src/web/assets.generated.ts
 * with all web assets inlined as a Map<path, {content, contentType}>.
 */
import { readdir } from "fs/promises";
import path from "path";

const DIST_DIR = path.join(import.meta.dir, "../dist/web");
const OUT_FILE = path.join(import.meta.dir, "../src/web/assets.generated.ts");

const MIME_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".ico": "image/x-icon",
};

async function collectFiles(dir: string, base: string = ""): Promise<{ path: string; fullPath: string }[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files: { path: string; fullPath: string }[] = [];
  for (const entry of entries) {
    const rel = base ? `${base}/${entry.name}` : entry.name;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...await collectFiles(full, rel));
    } else {
      files.push({ path: `/${rel}`, fullPath: full });
    }
  }
  return files;
}

const files = await collectFiles(DIST_DIR);

let output = `// Auto-generated by scripts/embed-assets.ts — do not edit\n\n`;
output += `export const ASSETS = new Map<string, { content: string; contentType: string }>();\n\n`;

for (const file of files) {
  const ext = path.extname(file.fullPath);
  const contentType = MIME_TYPES[ext] || "application/octet-stream";
  const raw = await Bun.file(file.fullPath).text();
  const escaped = raw.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
  output += `ASSETS.set("${file.path}", { content: \`${escaped}\`, contentType: "${contentType}" });\n`;
}

// Also map "/" to "/index.html"
output += `\nASSETS.set("/", ASSETS.get("/index.html")!);\n`;

await Bun.write(OUT_FILE, output);
console.log(`Embedded ${files.length} files into ${OUT_FILE}`);
